version: "2.7"

service:
  telegram_bot:
    command: "php bot.php"
    process_num: 1
    remain_after_exit: true
    restart_sec: 1
    env:
        - BOT_TOKEN: 5338016928:AAEEJyoCazgqeIWsdSTKEETRUR2-w9SZJ6M
