version: "2.7"

service:
  telegram_bot:
    command: "php -d extension=./vendor/swow/swow/ext/.libs/swow.so bot.php"
    remain_after_exit: true
    restart_sec: 1
    env:
        - BOT_TOKEN: 5338016928:AAEEJyoCazgqeIWsdSTKEETRUR2-w9SZJ6M
